import { PrismaClient, VacatureCategory } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Create admin user
  const hashedPassword = await bcrypt.hash("FlexiaAdmin2024!", 12);
  await prisma.user.upsert({
    where: { email: "admin@flexiajobs.nl" },
    update: {},
    create: {
      email: "admin@flexiajobs.nl",
      name: "Admin",
      hashedPassword,
      role: "ADMIN",
    },
  });
  console.log("Admin user created: admin@flexiajobs.nl");

  // Seed all vacatures
  const vacatures = [
    // CATERING
    {
      slug: "catering-den-haag-1",
      vacatureNumber: 1001,
      title: "Catering Medewerker - Den Haag",
      subtitle: "Evenementen & Feesten",
      description: "Word catering medewerker bij Flexia in Den Haag! Werk op feesten, bruiloften en bedrijfsevenementen.",
      longDescription: "Ben jij op zoek naar een dynamische baan in de catering? Als catering medewerker bij Flexia werk je op de mooiste locaties in Den Haag. Van bruiloften in stijlvolle venues tot grote bedrijfsevenementen - geen dag is hetzelfde! Je zorgt ervoor dat gasten een onvergetelijke ervaring hebben door professionele service te bieden.",
      seoContent: "Catering medewerker vacature Den Haag - werk op feesten, bruiloften en bedrijfsevenementen. Flexibele werktijden, geen ervaring nodig. Verdien €17 per uur (21+) bij Flexia. Solliciteer direct! Wij bieden gratis training en wekelijkse uitbetaling.",
      requirements: ["Geen ervaring nodig - wij trainen je!", "Minimaal 16 jaar", "Beschikbaar in weekenden", "Representatief voorkomen", "Teamspeler"],
      benefits: ["Flexibele werktijden", "Gratis training", "Wekelijkse uitbetaling", "Diverse locaties"],
      category: VacatureCategory.CATERING,
      imageKey: "catering",
      employmentType: ["FULL_TIME", "PART_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "catering-leiden-1",
      vacatureNumber: 1002,
      title: "Catering Medewerker - Leiden",
      subtitle: "Festivals & Events",
      description: "Catering medewerker gezocht voor festivals en events in Leiden!",
      longDescription: "Werk als catering medewerker op de leukste festivals en events in Leiden en omgeving. Je bent verantwoordelijk voor het serveren van eten en drinken, het opbouwen en afbreken van catering setups, en het zorgen voor een top ervaring voor bezoekers.",
      seoContent: "Catering medewerker vacature Leiden - werk op festivals en events. Flexibele werktijden, geen ervaring nodig. Verdien €17 per uur (21+) bij Flexia. Solliciteer direct voor catering werk in Leiden!",
      requirements: ["Geen ervaring vereist", "Minimaal 16 jaar", "Flexibel inzetbaar", "Fysiek fit", "Enthousiast en servicegericht"],
      benefits: ["Werk op leuke festivals", "Flexibele planning", "Wekelijkse uitbetaling", "Reiskostenvergoeding"],
      category: VacatureCategory.CATERING,
      imageKey: "catering",
      employmentType: ["PART_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    {
      slug: "catering-den-haag-2",
      vacatureNumber: 1003,
      title: "Catering Medewerker - Den Haag",
      subtitle: "Corporate Events",
      description: "Werk als catering medewerker op zakelijke events in Den Haag!",
      longDescription: "Specialiseer je in corporate catering in Den Haag. Werk op congressen, zakelijke bijeenkomsten en netwerkevenementen. Professionele omgeving met uitgebreide training in service en hospitality.",
      seoContent: "Corporate catering medewerker vacature Den Haag - werk op zakelijke events, congressen en netwerkevenementen. Professionele omgeving met uitgebreide training. Verdien €17 per uur (21+) plus goede fooien. Solliciteer nu!",
      requirements: ["Professionele uitstraling en representatief", "Geen ervaring nodig - corporate training", "Interesse in zakelijke wereld", "Betrouwbaar en punctueel", "Teamspeler met ambitie"],
      benefits: ["Werk op professioneel hoog niveau", "Doorgroeimogelijkheden naar leidinggevend", "Netwerken met professionals", "Uitstekend salaris en fooien"],
      category: VacatureCategory.CATERING,
      imageKey: "catering",
      employmentType: ["FULL_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "catering-leiden-2",
      vacatureNumber: 1004,
      title: "Catering Medewerker - Leiden",
      subtitle: "Bruiloften & Feesten",
      description: "Catering medewerker voor bruiloften en feesten in Leiden!",
      longDescription: "Werk als catering medewerker op de mooiste bruiloften en feesten in Leiden. Een feestelijke werkomgeving waar je gasten blij maakt op hun mooiste dag!",
      seoContent: "Catering medewerker vacature Leiden - bruiloften en feesten. Werk in een feestelijke omgeving. Geen ervaring nodig. Verdien €17 per uur (21+). Solliciteer nu bij Flexia!",
      requirements: ["Geen ervaring vereist", "Representatief voorkomen", "Beschikbaar in weekenden", "Gastvrij en servicegericht"],
      benefits: ["Feestelijke werkomgeving", "Flexibele uren", "Wekelijkse uitbetaling", "Gratis training"],
      category: VacatureCategory.CATERING,
      imageKey: "catering",
      employmentType: ["PART_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    // SPOELKEUKEN
    {
      slug: "spoelkeuken-den-haag-1",
      vacatureNumber: 2001,
      title: "Spoelkeuken Medewerker - Den Haag",
      subtitle: "Keuken Support",
      description: "Parttime afwas werk in Den Haag - ideaal naast je studie!",
      longDescription: "Werk parttime als spoelkeuken medewerker in Den Haag. Ideaal naast je studie of andere werkzaamheden! Duidelijke taken, een goed team en flexibele shifts. Je zorgt dat de keuken draait door alles schoon en georganiseerd te houden.",
      seoContent: "Parttime spoelkeuken medewerker vacature Den Haag - ideaal naast studie! Werk als afwasser in de horeca met flexibele avonddiensten. Geen ervaring of diploma vereist. Verdien €17 per uur (21+) plus fooiendeling. Direct aan de slag mogelijk. Solliciteer nu!",
      requirements: ["Geen ervaring nodig", "Parttime beschikbaar (avonddiensten)", "Fysiek fit", "Betrouwbaar en punctueel"],
      benefits: ["Ideaal naast studie", "Direct aan de slag", "Wekelijks uitbetaald", "Fooiendeling"],
      category: VacatureCategory.SPOELKEUKEN,
      imageKey: "chef",
      employmentType: ["PART_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "spoelkeuken-leiden-1",
      vacatureNumber: 2002,
      title: "Spoelkeuken Medewerker - Leiden",
      subtitle: "Keuken Support",
      description: "Fulltime spoelkeuken medewerker in Leiden!",
      longDescription: "Werk fulltime als spoelkeuken medewerker in Leiden. Je bent essentieel voor het draaiende houden van de keuken. Moderne faciliteiten, een goed team en doorgroeimogelijkheden naar keukenhulp. Direct aan de slag mogelijk!",
      seoContent: "Fulltime spoelkeuken medewerker vacature in Leiden. Werk in een professionele keuken met moderne apparatuur. Geen ervaring of diploma vereist. Verdien €17 per uur (21+) plus fooiendeling. Direct aan de slag mogelijk. Solliciteer nu!",
      requirements: ["Geen ervaring nodig", "Fulltime beschikbaar (40 uur)", "Fysiek fit en gemotiveerd", "Betrouwbaar en punctueel"],
      benefits: ["Direct aan de slag", "Wekelijks uitbetaald", "Fooiendeling", "Doorgroeimogelijkheden"],
      category: VacatureCategory.SPOELKEUKEN,
      imageKey: "chef",
      employmentType: ["FULL_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    {
      slug: "spoelkeuken-den-haag-2",
      vacatureNumber: 2003,
      title: "Spoelkeuken Medewerker - Den Haag",
      subtitle: "Keuken Support",
      description: "Fulltime in professionele keukens met doorgroei!",
      longDescription: "Fulltime werk als spoelkeuken medewerker in professionele keukens in Den Haag. Moderne faciliteiten, professioneel team en doorgroeimogelijkheden. Direct aan de slag mogelijk!",
      seoContent: "Spoelkeuken medewerker vacature Den Haag - fulltime in moderne keuken. Werk in professionele omgeving met doorgroeimogelijkheden naar keukenhulp. Geen ervaring of diploma vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring nodig - training aanwezig", "Fulltime beschikbaar (40 uur)", "Fysiek fit en gemotiveerd", "Betrouwbaar en punctueel", "Kan goed tegen drukte"],
      benefits: ["Moderne keuken met nieuwe apparatuur", "Direct aan de slag", "Fooiendeling", "Doorgroeimogelijkheden"],
      category: VacatureCategory.SPOELKEUKEN,
      imageKey: "chef",
      employmentType: ["FULL_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    // KEUKENHULP
    {
      slug: "keukenhulp-den-haag-1",
      vacatureNumber: 3001,
      title: "Keukenhulp - Den Haag",
      subtitle: "Culinair Assistant",
      description: "Fulltime keukenhulp in Den Haag - leer van professionals!",
      longDescription: "Werk fulltime als keukenhulp in Den Haag. Leer het vak van ervaren koks en bouw een carrière in de horeca. Je helpt met voorbereiden, opruimen en alles wat nodig is om de keuken draaiende te houden.",
      seoContent: "Fulltime keukenhulp vacature Den Haag - leer van professionals! Word assistent kok en leer het vak. Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring vereist - wel motivatie", "Fulltime beschikbaar", "Interesse in koken", "Hygiënisch werken"],
      benefits: ["Leer van professionals", "Direct aan de slag", "Wekelijks uitbetaald", "Doorgroeimogelijkheden"],
      category: VacatureCategory.KEUKENHULP,
      imageKey: "chef",
      employmentType: ["FULL_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "keukenhulp-leiden-1",
      vacatureNumber: 3002,
      title: "Keukenhulp - Leiden",
      subtitle: "Culinair Assistant",
      description: "Fulltime keukenhulp in Leiden - werk in een moderne keuken!",
      longDescription: "Werk fulltime als keukenhulp in een moderne keuken in Leiden. Je werkt samen met ervaren koks en leert alle aspecten van het keukenvak.",
      seoContent: "Fulltime keukenhulp vacature Leiden - moderne keuken! Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring vereist - wel motivatie", "Fulltime beschikbaar", "Leergierig en enthousiast", "Hygiënisch werken"],
      benefits: ["Moderne keuken", "Direct aan de slag", "Wekelijks uitbetaald", "Doorgroeimogelijkheden"],
      category: VacatureCategory.KEUKENHULP,
      imageKey: "chef",
      employmentType: ["FULL_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    {
      slug: "keukenhulp-den-haag-2",
      vacatureNumber: 3003,
      title: "Keukenhulp - Den Haag",
      subtitle: "Culinair Assistant",
      description: "Parttime in professionele keuken - centrum locatie!",
      longDescription: "Werk parttime als keukenhulp in professionele keukens in Den Haag centrum. Leer koken in een dynamische omgeving. Gezellig team, flexibele werktijden en goede bereikbaarheid!",
      seoContent: "Keukenhulp vacature Den Haag centrum - parttime werk, leer koken in professionele keuken. Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring vereist - wel motivatie", "Parttime beschikbaar (16-32 uur)", "Interesse in koken en eten", "Flexibel en betrouwbaar", "Hygiënisch werken"],
      benefits: ["Centrum locatie - goed bereikbaar", "Direct aan de slag", "Gezellig team", "Leer professioneel koken"],
      category: VacatureCategory.KEUKENHULP,
      imageKey: "chef",
      employmentType: ["PART_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "keukenhulp-leiden-2",
      vacatureNumber: 3004,
      title: "Keukenhulp - Leiden",
      subtitle: "Culinair Assistant",
      description: "Parttime - leer van de beste koks in de regio!",
      longDescription: "Parttime keukenhulp in Leiden. Leer van de beste koks in de regio! Flexibele roosters, jong team en doorgroei naar zelfstandig kok.",
      seoContent: "Keukenhulp vacature Leiden - parttime werk, leer van topkoks. Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring vereist - passie voor koken wel", "Parttime beschikbaar (16-32 uur)", "Leergierig en enthousiast over eten", "Flexibel en gemotiveerd", "Oog voor detail"],
      benefits: ["Leer van award-winning chefs", "Flexibele werktijden", "Jong team met passie", "Doorgroei naar kok"],
      category: VacatureCategory.KEUKENHULP,
      imageKey: "chef",
      employmentType: ["PART_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    {
      slug: "keukenhulp-den-haag-3",
      vacatureNumber: 3005,
      title: "Keukenhulp - Den Haag",
      subtitle: "Culinair Assistant",
      description: "Fulltime in restaurant - fooiendeling en carrièrekansen!",
      longDescription: "Fulltime keukenhulp voor een prachtig restaurant in Den Haag. Professionele keuken, fooiendeling en doorgroei naar sous chef mogelijk.",
      seoContent: "Keukenhulp vacature Den Haag - fulltime restaurant met fooiendeling en carrièrekansen. Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Geen ervaring vereist - interesse in gastronomie wel", "Fulltime beschikbaar (40 uur)", "Passie voor fine dining en culinair", "Representatief en professioneel", "Leergierig met oog voor kwaliteit"],
      benefits: ["Restaurant setting - fine dining", "Professionele keuken en producten", "Uitstekende fooiendeling", "Doorgroei naar sous/head chef"],
      category: VacatureCategory.KEUKENHULP,
      imageKey: "chef",
      employmentType: ["FULL_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    // BEDIENING
    {
      slug: "bediening-den-haag-1",
      vacatureNumber: 4001,
      title: "Bediening Medewerker - Den Haag",
      subtitle: "Horeca Service",
      description: "Fulltime bediening in restaurant in Den Haag centrum!",
      longDescription: "Werk fulltime als bediening medewerker in een restaurant in Den Haag centrum. Je staat in direct contact met gasten en zorgt voor een geweldige eetervaring.",
      seoContent: "Fulltime bediening medewerker vacature Den Haag centrum. Geen ervaring vereist - wij bieden gratis training. Verdien €17 per uur (21+) plus goede fooien. Solliciteer nu!",
      requirements: ["Geen ervaring nodig - training aanwezig", "Fulltime beschikbaar", "Representatief voorkomen", "Sociaal en gastvrij"],
      benefits: ["Direct aan de slag", "Wekelijks uitbetaald", "Goede fooiendeling", "Doorgroeimogelijkheden"],
      category: VacatureCategory.BEDIENING,
      imageKey: "bediening",
      employmentType: ["FULL_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "bediening-leiden-1",
      vacatureNumber: 4002,
      title: "Bediening Medewerker - Leiden",
      subtitle: "Horeca Service",
      description: "Ontwikkel je in fine dining met professionele training!",
      longDescription: "Werk fulltime als bediening medewerker in gerenommeerde restaurants in Leiden. Leer fine dining service, wijnkennis en gastronomie.",
      seoContent: "Bediening medewerker vacature Leiden - fulltime werk in fine dining. Geen ervaring vereist. Verdien €17 per uur (21+) plus uitstekende fooien. Solliciteer nu!",
      requirements: ["Fulltime beschikbaar (40 uur)", "Representatief voorkomen en verzorgd", "Geen ervaring nodig - uitgebreide training", "Leergierig en gepassioneerd", "Nederlands en Engels"],
      benefits: ["Leer fine dining en wijnkennis", "Professionele ontwikkeling en trainingen", "Doorgroei naar sommelier/manager", "Uitstekende fooien en vast contract"],
      category: VacatureCategory.BEDIENING,
      imageKey: "bediening",
      employmentType: ["FULL_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
    {
      slug: "bediening-den-haag-2",
      vacatureNumber: 4003,
      title: "Bediening Medewerker - Den Haag",
      subtitle: "Horeca Service",
      description: "Werk op gezellige terrassen en in bruisende bars!",
      longDescription: "Werk parttime op de gezelligste terrassen en in de leukste bars van Den Haag! Relaxte sfeer, leuk team en direct contact met vaste gasten.",
      seoContent: "Bediening medewerker vacature Den Haag - terras en bar werk. Parttime, geen ervaring nodig. Verdien €17 per uur (21+) plus goede fooien. Solliciteer nu!",
      requirements: ["Parttime beschikbaar (vooral zomer)", "Sociaal, gastvrij en vlot in contact", "Geen ervaring nodig - wel enthousiasme", "Flexibele beschikbaarheid (avonden/weekenden)", "Nederlands (Engelse basis handig)"],
      benefits: ["Gezellige terras sfeer in zomer", "Leuk, informeel team", "Goede fooien (extra in zomer)", "Flexibele uren"],
      category: VacatureCategory.BEDIENING,
      imageKey: "bediening",
      employmentType: ["PART_TIME"],
      location: "Den Haag",
      salary: 17.00,
    },
    {
      slug: "bediening-leiden-2",
      vacatureNumber: 4004,
      title: "Bediening Medewerker - Leiden",
      subtitle: "Horeca Service",
      description: "Parttime dagdiensten in gezellige lunchrooms!",
      longDescription: "Werk parttime in gezellige lunchrooms en ontbijtcafés in Leiden. Alleen dagdiensten, geen avond- of nachtwerk! Relaxte sfeer en leuk contact met vaste gasten.",
      seoContent: "Bediening medewerker vacature Leiden - parttime dagdiensten, geen avondwerk! Geen ervaring vereist. Verdien €17 per uur (21+). Solliciteer nu!",
      requirements: ["Parttime beschikbaar (dagdiensten 8-17u)", "Gastvrij, vriendelijk en klantvriendelijk", "Geen ervaring nodig - simpele training", "Ochtend/middag beschikbaar (geen avonden)", "Flexibel en betrouwbaar"],
      benefits: ["Alleen dagdiensten - geen avondwerk", "Ideaal naast studie", "Gezellige lunchroom sfeer", "Vaste roosters, weken vooruit"],
      category: VacatureCategory.BEDIENING,
      imageKey: "bediening",
      employmentType: ["PART_TIME"],
      location: "Leiden",
      salary: 17.00,
    },
  ];

  for (const v of vacatures) {
    await prisma.vacature.upsert({
      where: { slug: v.slug },
      update: v,
      create: v,
    });
  }

  console.log(`Seeded ${vacatures.length} vacatures`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
